"""
Build 10,000-word frequency dictionaries for Spanish and Italian.

Sources: Hermit Dave FrequencyWords (OpenSubtitles 2018 corpus)
Model:   claude-haiku-4-5-20251001
Output:  app/services/freq_dict_es.py
         app/services/freq_dict_it.py

Usage:
    cd /path/to/dvnr
    source .venv/bin/activate
    python scripts/build_freq_dict/build.py --lang es
    python scripts/build_freq_dict/build.py --lang it
    python scripts/build_freq_dict/build.py --lang es --lang it   # both

Resume:  Re-running automatically skips words already in the output file.

Cost estimate: ~$0.20 per language at Haiku pricing.
"""

import argparse
import asyncio
import json
import os
import re
import sys
import urllib.request
from pathlib import Path

import anthropic

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parents[2]
BATCH_SIZE = 50
TOP_N = 10_000

LANGUAGES = {
    "es": {
        "name": "Spanish",
        "url": "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/es/es_50k.txt",
        "known_module": "app.services.known_lemmas_es",
        "known_var": "KNOWN_LEMMAS_ES",
        "output": REPO_ROOT / "app/services/freq_dict_es.py",
        "var": "FREQ_DICT_ES",
    },
    "it": {
        "name": "Italian",
        "url": "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/it/it_50k.txt",
        "known_module": None,
        "known_var": None,
        "output": REPO_ROOT / "app/services/freq_dict_it.py",
        "var": "FREQ_DICT_IT",
    },
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

CACHE_DIR = Path(__file__).parent / "cache"


def fetch_frequency_list(url: str, top_n: int) -> list[str]:
    """Download Hermit Dave list (cached locally), return top_n word forms."""
    CACHE_DIR.mkdir(exist_ok=True)
    filename = url.split("/")[-1]  # e.g. es_50k.txt
    cache_path = CACHE_DIR / filename

    if cache_path.exists():
        print(f"  Using cached: {cache_path}")
        raw = cache_path.read_text(encoding="utf-8")
    else:
        print(f"  Downloading: {url}")
        with urllib.request.urlopen(url, timeout=30) as resp:
            raw = resp.read().decode("utf-8")
        cache_path.write_text(raw, encoding="utf-8")
        print(f"  Saved to: {cache_path}")

    words = []
    for line in raw.splitlines():
        parts = line.strip().split()
        if not parts:
            continue
        word = parts[0].lower()
        # Skip if not purely alphabetic (drop contractions, digits, punctuation)
        if not re.fullmatch(r"[a-záéíóúüñàèìòùäöüß]+", word):
            continue
        words.append(word)
        if len(words) >= top_n:
            break
    print(f"  Got {len(words)} words after filtering")
    return words


def load_existing_output(path: Path, var: str) -> dict[str, str]:
    """Parse an already-written output file and return its dict contents."""
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8")
    # Extract dict literal between { and the final }
    m = re.search(rf"{var}\s*=\s*\{{(.+)\}}", text, re.DOTALL)
    if not m:
        return {}
    body = m.group(1)
    result = {}
    for line in body.splitlines():
        m2 = re.match(r'\s*"(.+?)"\s*:\s*"(.+?)",?\s*$', line)
        if m2:
            result[m2.group(1)] = m2.group(2)
    return result


def load_known_lemmas(lang_cfg: dict) -> set[str]:
    """Return set of keys already in known_lemmas_XX.py, or empty set."""
    module = lang_cfg["known_module"]
    if not module:
        return set()
    # Import dynamically
    import importlib
    sys.path.insert(0, str(REPO_ROOT))
    mod = importlib.import_module(module)
    known: dict = getattr(mod, lang_cfg["known_var"])
    return set(known.keys())


def write_output_file(path: Path, var: str, lang_name: str, data: dict[str, str]) -> None:
    """Write the complete Python dict file."""
    lines = [
        f'"""',
        f"Top {len(data):,}-word {lang_name} frequency dictionary.",
        f"",
        f"Keys are lower-cased word forms from the Hermit Dave FrequencyWords list",
        f"(OpenSubtitles 2018 corpus). Values are concise English definitions.",
        f"",
        f"Auto-generated by scripts/build_freq_dict/build.py — do not edit by hand.",
        f'"""',
        f"",
        f"{var}: dict[str, str] = {{",
    ]
    for word, defn in sorted(data.items()):
        escaped = defn.replace('"', '\\"')
        lines.append(f'    "{word}": "{escaped}",')
    lines.append("}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


# ---------------------------------------------------------------------------
# Claude batching
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """\
You are a bilingual dictionary. Given a list of {lang} words, return a JSON object
mapping each word to a concise English definition (5 words or fewer).

Rules:
- Use the base/lemma form for the definition (e.g. for "corriendo" give "to run")
- For verbs use infinitive form: "to ..."
- For nouns give the singular form meaning
- Keep definitions extremely short: 1-5 words
- If a word is a proper noun, name, or abbreviation with no clear definition, use null
- Return ONLY the JSON object, no other text
"""

async def fetch_batch(
    client: anthropic.AsyncAnthropic,
    words: list[str],
    lang_name: str,
) -> dict[str, str | None]:
    """Call Claude Haiku for one batch, return {word: definition_or_null}."""
    word_list = "\n".join(f"- {w}" for w in words)
    prompt = f"Words to define ({lang_name}):\n{word_list}"

    response_text = ""
    async with client.messages.stream(
        model="claude-haiku-4-5-20251001",
        max_tokens=1024,
        system=SYSTEM_PROMPT.format(lang=lang_name),
        messages=[
            {"role": "user", "content": prompt},
            {"role": "assistant", "content": "{"},
        ],
    ) as stream:
        async for chunk in stream.text_stream:
            response_text += chunk

    # Prepend the prefill brace
    response_text = "{" + response_text
    # Trim anything after the closing brace (safety)
    brace_end = response_text.rfind("}")
    if brace_end != -1:
        response_text = response_text[: brace_end + 1]

    try:
        return json.loads(response_text)
    except json.JSONDecodeError:
        print(f"\n  WARNING: JSON parse failed for batch. Raw:\n{response_text[:300]}")
        return {}


async def build_lang(lang: str) -> None:
    lang_cfg = LANGUAGES[lang]
    lang_name = lang_cfg["name"]
    output_path = lang_cfg["output"]
    var = lang_cfg["var"]

    print(f"\n{'='*60}")
    print(f"Building {lang_name} frequency dictionary")
    print(f"{'='*60}")

    # Load Anthropic client
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        # Try loading from .env
        env_path = REPO_ROOT / ".env"
        if env_path.exists():
            for line in env_path.read_text().splitlines():
                if line.startswith("ANTHROPIC_API_KEY="):
                    api_key = line.split("=", 1)[1].strip().strip('"').strip("'")
                    break
    if not api_key:
        print("ERROR: ANTHROPIC_API_KEY not found in environment or .env file")
        sys.exit(1)

    client = anthropic.AsyncAnthropic(api_key=api_key)

    # Fetch word list
    print("\n[1] Fetching frequency list...")
    all_words = fetch_frequency_list(lang_cfg["url"], TOP_N)

    # Load already-known lemmas (skip them)
    print("\n[2] Loading known lemmas to skip...")
    known = load_known_lemmas(lang_cfg)
    print(f"  Skipping {len(known)} known lemma entries")

    # Load already-fetched words (resume support)
    print("\n[3] Checking for existing output to resume from...")
    already_done = load_existing_output(output_path, var)
    print(f"  Already have {len(already_done)} definitions")

    # Words we still need
    need = [
        w for w in all_words
        if w not in known and w not in already_done
    ]
    print(f"\n  Words to fetch: {len(need)}")

    if not need:
        print("\nNothing to do — all words already defined.")
        # Still write file to ensure it's up to date
        combined = {**already_done}
        write_output_file(output_path, var, lang_name, combined)
        print(f"Output: {output_path}")
        return

    # Fetch in batches
    print(f"\n[4] Fetching definitions ({len(need)} words, {BATCH_SIZE}/batch)...")
    results: dict[str, str] = {**already_done}

    batches = [need[i : i + BATCH_SIZE] for i in range(0, len(need), BATCH_SIZE)]
    total_batches = len(batches)

    for i, batch in enumerate(batches, 1):
        print(f"  Batch {i}/{total_batches} ({len(batch)} words)...", end=" ", flush=True)
        batch_result = await fetch_batch(client, batch, lang_name)

        added = 0
        for word in batch:
            defn = batch_result.get(word)
            if defn and defn != "null" and isinstance(defn, str):
                results[word] = defn
                added += 1

        print(f"got {added}/{len(batch)}")

        # Write checkpoint after every batch (resume support)
        write_output_file(output_path, var, lang_name, results)

        # Brief pause to avoid rate limiting (Haiku: 50 RPM on tier 1)
        if i < total_batches:
            await asyncio.sleep(1.2)

    print(f"\n[5] Done.")
    print(f"  Total entries: {len(results)}")
    print(f"  Output: {output_path}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

async def main() -> None:
    parser = argparse.ArgumentParser(description="Build DVNR frequency dictionaries")
    parser.add_argument(
        "--lang",
        action="append",
        choices=["es", "it"],
        dest="langs",
        help="Language(s) to build (can specify multiple times)",
    )
    args = parser.parse_args()

    langs = args.langs or ["es", "it"]
    for lang in langs:
        await build_lang(lang)


if __name__ == "__main__":
    asyncio.run(main())
