"""
Top ~300 most common Spanish lemmas with concise English definitions.
Used to pre-fill definition_lemma without burning Claude output tokens.
Covers only the highest-frequency vocabulary a learner is most likely to know,
leaving less common words for Claude to define.
"""

KNOWN_LEMMAS_ES: dict[str, str] = {
    # Core verbs - be/have
    "ser": "to be (identity/nature)",
    "estar": "to be (state/location)",
    "haber": "to have (auxiliary)",
    "tener": "to have, to possess",
    # Core verbs - modal/semi-modal
    "poder": "to be able to, can",
    "deber": "to owe, must, should",
    "querer": "to want, to love",
    "saber": "to know (fact/how)",
    "necesitar": "to need",
    # Core verbs - motion
    "ir": "to go",
    "venir": "to come",
    "llegar": "to arrive",
    "salir": "to leave, to go out",
    "entrar": "to enter, to come in",
    "volver": "to return, to come back",
    "pasar": "to pass, to happen",
    "seguir": "to follow, to continue",
    "quedar": "to remain, to be left",
    "quedarse": "to stay, to remain",
    # Core verbs - action
    "hacer": "to do, to make",
    "dar": "to give",
    "tomar": "to take",
    "poner": "to put, to place",
    "dejar": "to leave, to let",
    "llevar": "to carry, to take, to wear",
    "traer": "to bring",
    "sacar": "to take out, to remove",
    "usar": "to use",
    # Core verbs - communication
    "decir": "to say, to tell",
    "hablar": "to speak, to talk",
    "llamar": "to call",
    "preguntar": "to ask",
    "responder": "to answer, to respond",
    "contar": "to tell, to count",
    "escribir": "to write",
    "leer": "to read",
    "escuchar": "to listen",
    "oír": "to hear",
    # Core verbs - perception/cognition
    "ver": "to see",
    "mirar": "to look at, to watch",
    "conocer": "to know (person/place)",
    "pensar": "to think",
    "creer": "to believe, to think",
    "recordar": "to remember",
    "olvidar": "to forget",
    "entender": "to understand",
    "sentir": "to feel, to sense",
    "parecer": "to seem, to appear",
    # Core verbs - existence/change
    "vivir": "to live",
    "morir": "to die",
    "nacer": "to be born",
    "cambiar": "to change",
    "perder": "to lose",
    "ganar": "to win, to earn",
    "empezar": "to begin, to start",
    "terminar": "to finish, to end",
    "acabar": "to finish, to end up",
    "esperar": "to wait, to hope",
    "intentar": "to try, to attempt",
    "ayudar": "to help",
    "trabajar": "to work",
    "estudiar": "to study",
    "jugar": "to play",
    "comer": "to eat",
    "beber": "to drink",
    "dormir": "to sleep",
    "levantarse": "to get up, to rise",
    "sentarse": "to sit down",
    "reír": "to laugh",
    "llorar": "to cry",
    "gustar": "to like (lit. to please)",
    "amar": "to love",
    "existir": "to exist",
    "ocurrir": "to occur, to happen",
    "resultar": "to turn out, to result",
    "servir": "to serve",
    "significar": "to mean, to signify",
    "importar": "to matter, to import",
    "faltar": "to be missing, to lack",
    "doler": "to hurt, to ache",
    "valer": "to be worth",
    "durar": "to last",
    # Nouns - people
    "persona": "person",
    "gente": "people",
    "hombre": "man",
    "mujer": "woman",
    "niño": "boy, child",
    "niña": "girl, child",
    "joven": "young person, youth",
    "familia": "family",
    "padre": "father, parent",
    "madre": "mother",
    "hijo": "son, child",
    "hija": "daughter",
    "hermano": "brother",
    "hermana": "sister",
    "abuelo": "grandfather",
    "abuela": "grandmother",
    "esposo": "husband",
    "esposa": "wife",
    "amigo": "friend (male)",
    "amiga": "friend (female)",
    "señor": "mister, sir, gentleman",
    "señora": "madam, lady, Mrs.",
    "maestro": "teacher (male)",
    "maestra": "teacher (female)",
    "profesor": "professor, teacher (male)",
    "profesora": "professor, teacher (female)",
    "estudiante": "student",
    # Nouns - body
    "cuerpo": "body",
    "cabeza": "head",
    "cara": "face",
    "ojo": "eye",
    "boca": "mouth",
    "mano": "hand",
    "brazo": "arm",
    "pierna": "leg",
    "pie": "foot",
    "corazón": "heart",
    "voz": "voice",
    # Nouns - place
    "lugar": "place",
    "ciudad": "city",
    "pueblo": "town, village, people",
    "país": "country",
    "mundo": "world",
    "casa": "house, home",
    "cuarto": "room",
    "calle": "street",
    "camino": "road, path, way",
    "escuela": "school",
    "universidad": "university",
    # Nouns - time
    "tiempo": "time, weather",
    "momento": "moment",
    "vez": "time (occurrence)",
    "hora": "hour, time",
    "día": "day",
    "noche": "night",
    "tarde": "afternoon, evening",
    "mañana": "morning, tomorrow",
    "semana": "week",
    "mes": "month",
    "año": "year",
    # Nouns - objects/things
    "cosa": "thing",
    "libro": "book",
    "papel": "paper",
    "mesa": "table",
    "ropa": "clothes, clothing",
    "dinero": "money",
    "comida": "food",
    "agua": "water",
    "casa": "house, home",
    # Nouns - abstract
    "vida": "life",
    "muerte": "death",
    "amor": "love",
    "miedo": "fear",
    "problema": "problem",
    "idea": "idea",
    "palabra": "word",
    "pregunta": "question",
    "respuesta": "answer, response",
    "historia": "history, story",
    "verdad": "truth",
    "razón": "reason",
    "manera": "way, manner",
    "forma": "form, shape, way",
    "parte": "part",
    "tipo": "type, kind",
    "nombre": "name",
    "número": "number",
    "trabajo": "work, job",
    "sueño": "dream, sleep",
    "luz": "light",
    "silencio": "silence",
    "nombre": "name",
    # Adjectives - core only
    "bueno": "good",
    "malo": "bad",
    "grande": "big, great",
    "pequeño": "small, little",
    "nuevo": "new",
    "viejo": "old",
    "largo": "long",
    "corto": "short",
    "alto": "tall, high",
    "bajo": "low, short",
    "rápido": "fast, quick",
    "lento": "slow",
    "fuerte": "strong",
    "fácil": "easy",
    "difícil": "difficult",
    "importante": "important",
    "mismo": "same, itself",
    "otro": "other, another",
    "último": "last, latest",
    "primero": "first",
    "siguiente": "following, next",
    "verdadero": "true, real",
    "claro": "clear, light",
    "blanco": "white",
    "negro": "black",
    "rojo": "red",
    "azul": "blue",
    "verde": "green",
    "solo": "alone, only",
    "triste": "sad",
    "contento": "happy, content",
    "muerto": "dead",
    "vivo": "alive",
    # Adverbs - core only
    "muy": "very",
    "mucho": "a lot, much",
    "poco": "a little, few",
    "más": "more",
    "menos": "less",
    "también": "also, too",
    "tampoco": "neither, not either",
    "siempre": "always",
    "nunca": "never",
    "ya": "already, now",
    "todavía": "still, yet",
    "ahora": "now",
    "antes": "before",
    "después": "after, later",
    "aquí": "here",
    "allí": "there",
    "bien": "well, good",
    "mal": "badly, bad",
    "así": "like this, so",
    "casi": "almost",
    "sólo": "only, just",
    "apenas": "hardly, barely, just",
    "incluso": "even, including",
    "además": "moreover, besides",
    "acaso": "perhaps, maybe",
    "quizás": "maybe, perhaps",
    # Prepositions / conjunctions
    "de": "of, from",
    "en": "in, on, at",
    "a": "to, at",
    "con": "with",
    "por": "for, by, through",
    "para": "for, in order to",
    "sin": "without",
    "sobre": "on, about, over",
    "entre": "between, among",
    "hasta": "until, up to",
    "desde": "from, since",
    "durante": "during",
    "hacia": "toward",
    "del": "of the (contraction de+el)",
    "al": "to the (contraction a+el)",
    "que": "that, which, who",
    "como": "as, like, how",
    "cuando": "when",
    "donde": "where",
    "si": "if",
    "aunque": "although, even though",
    "porque": "because",
    "pues": "well, since, so",
    "pero": "but",
    "sino": "but rather, but instead",
    "ni": "neither, nor",
    "mientras": "while, whereas",
    # Pronouns
    "yo": "I",
    "tú": "you (informal)",
    "él": "he",
    "ella": "she",
    "nosotros": "we",
    "ellos": "they (masc.)",
    "ellas": "they (fem.)",
    "usted": "you (formal)",
    "ustedes": "you all (formal/Latin America)",
    "me": "me, myself",
    "te": "you, yourself",
    "se": "himself/herself/itself/themselves (reflexive)",
    "nos": "us, ourselves",
    "le": "him, her, you (indirect object)",
    "lo": "him, it (direct object)",
    "la": "her, it (direct object)",
    "les": "them, you all (indirect object)",
    "los": "them (masc. direct object)",
    "las": "them (fem. direct object)",
    "su": "his, her, its, your (formal)",
    "nuestro": "our",
    "este": "this (masc.)",
    "esta": "this (fem.)",
    "ese": "that (masc.)",
    "esa": "that (fem.)",
    "esto": "this (neuter)",
    "eso": "that (neuter)",
    "algo": "something",
    "alguien": "someone",
    "nada": "nothing",
    "nadie": "nobody, no one",
    "todo": "everything, all",
    "todos": "everyone, all",
    "cada": "each, every",
    "cual": "which",
    "quien": "who",
    # Numbers
    "uno": "one",
    "dos": "two",
    "tres": "three",
    "cuatro": "four",
    "cinco": "five",
    "seis": "six",
    "siete": "seven",
    "ocho": "eight",
    "nueve": "nine",
    "diez": "ten",
    "veinte": "twenty",
    "cien": "one hundred",
    "mil": "one thousand",
    # Misc high-frequency
    "hay": "there is, there are",
    "ahí": "there, right there",
    "qué": "what, how (exclamation)",
    "quién": "who",
    "cuál": "which",
    "cuánto": "how much",
    "dónde": "where",
    "cuándo": "when",
    "cómo": "how",
}
